run:
  deadline: 5m
  skip-files: []
linters-settings:
  gosec:
    excludes:
      - G104
      - G307
  govet:
    check-shadowing: true
  gocyclo:
    min-complexity: 12
  maligned:
    suggest-new: true
  goconst:
    min-len: 3
    min-occurrences: 3
  misspell:
    locale: US
    ignore-words:
      - listend
      - analyses
linters:
  enable:
    - vet
    - golint
    - gofmt
    - deadcode
    - varcheck
    - structcheck
    - misspell
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - gosec
issues:
  exclude-use-default: false
  max-per-linter: 0
  max-same-issues: 0
  exclude: []
  exclude-rules:
      #Ignore gocui funcs
    - text: Error return value of `g.DeleteView` is not checked
      linters:
        - errcheck
    - text: Error return value of `g.SetCurrentView` is not checked
      linters:
        - errcheck
    - text: Error return value of `*.SetCursor` is not checked
      linters:
        - errcheck
      #Ignore shadowed err and ctx variables
    - text: declaration of "err" shadows declaration at *
      linters:
        - govet
    - text: declaration of "ctx" shadows declaration at *
      linters:
        - govet
      #Ignore comments for KeyBinding Handler funcs
    - path: internal/pkg/keybindings/listhandlers.go
      linters:
        - golint
    - path: internal/pkg/keybindings/commandpanelhandlers.go
      linters:
        - golint
    - path: internal/pkg/keybindings/itemhandlers.go
      linters:
        - golint
    - path: internal/pkg/keybindings/globalhandlers.go
      linters:
        - golint
    - path: internal/pkg/*
      linters:
        - golint
