name: release

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:  
  build-xpath:
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2

    - name: CI Tooling
      run: sudo apt update && sudo apt install build-essential fuse -y
    
    - name: Build devcontainer for tooling
      run: sudo -E make devcontainer

    - name: Build the Docker image, run tests and publish(on master only)
      run: sudo -E make devcontainer-release
      env:
        GITHUB_TOKEN: ${{ secrets.GHACTIONS_SECRET }}
        BUILD_NUMBER: ${{ github.run_id }}
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        IS_CI: 1
        IS_PR: ${{ github.head_ref }}
        BRANCH: ${{ github.ref }}
